language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  homebrew:
    packages:
      - ghostscript
      - md5sha1sum
      - icu4c
      - freetype
      - fribidi
      - gmp
      - graphite2
      - hunspell
      - jpeg
      - libpng
      - libtiff
      - libzzip
      - log4cxx
      - mpfr
      - openssl
      - pixman
      - popt
      - qt
      - uriparser
      - xz

matrix:
  allow_failures:
    - os: osx
      osx_image: xcode12
      before_script: ./BuildUtilities/ci/travis/osx/before_script.sh
      script: ./BuildUtilities/ci/travis/osx/script.sh
      after_failure: ./BuildUtilities/ci/travis/osx/after_failure.sh
  include:
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=fedora
      - MIKTEX_LINUX_DIST_VERSION=32
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=debian
      - MIKTEX_LINUX_DIST_VERSION=10
      - MIKTEX_LINUX_DIST_CODE_NAME=buster
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=debian
      - MIKTEX_LINUX_DIST_VERSION=9
      - MIKTEX_LINUX_DIST_CODE_NAME=stretch
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=ubuntu
      - MIKTEX_LINUX_DIST_VERSION=20.04
      - MIKTEX_LINUX_DIST_CODE_NAME=focal
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=ubuntu
      - MIKTEX_LINUX_DIST_VERSION=16.04
      - MIKTEX_LINUX_DIST_CODE_NAME=xenial
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=fedora
      - MIKTEX_LINUX_DIST_VERSION=28
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
      - MIKTEX_LINUX_DIST=opensuse
      - MIKTEX_LINUX_DIST_VERSION=15
      script: ./BuildUtilities/ci/travis/docker/script.sh
      after_failure: ./BuildUtilities/ci/travis/docker/after_failure.sh

notifications:
  email: false
